<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function getRoleForAccountAndProject($account_id, $project_id)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT r.name as role
                    FROM NeblionScrumBundle:Member m
                    INNER JOIN m.role r
                    INNER JOIN m.account a
                    INNER JOIN m.project p
                    WHERE p.id = :project_id
                    AND a.id = :account_id'
                )
                ->setParameter('project_id', $project_id)
                ->setParameter('account_id', $account_id)
                ->getSingleScalarResult();
    }
    
}
