<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends EntityRepository
{
    public function getListForProject($project_id, $returnQuery = false)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT f FROM NeblionScrumBundle:Feature f
                    INNER JOIN f.project p
                    WHERE p.id = :project_id
                    ORDER BY f.name'
                )
                ->setParameter('project_id', $project_id);
        if (!$returnQuery) {
            return $query->getArrayResult();
        }
        
        return $query;
    }
    
}