<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetrospectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetrospectiveRepository extends EntityRepository
{
    public function getForSprint($sprint_id)
    {
        return $this->getEntityManager()->createQuery(
                'SELECT r, s, u, p
                    FROM NeblionScrumBundle:Retrospective r
                    INNER JOIN r.sprint s
                    INNER JOIN r.user u
                    LEFT JOIN u.profile p
                    WHERE s.id = :sprint_id')
                ->setParameter('sprint_id', $sprint_id)
                ->getResult();
    }
    
    public function load($id)
    {
        return $this->getEntityManager()->createQuery(
                'SELECT r, s, u, pr, p
                    FROM NeblionScrumBundle:Retrospective r
                    INNER JOIN r.sprint s
                    INNER JOIN r.user u
                    INNER JOIN s.projectRelease pr
                    INNER JOIN pr.project p
                    WHERE r.id = :id')
                ->setParameter('id', $id)
                ->getOneOrNullResult();
    }
}