<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    public function load($id)
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT r, s, sp, p, f, pr, ss
                    FROM NeblionScrumBundle:Review r
                    INNER JOIN r.story s
                    INNER JOIN s.status ss
                    INNER JOIN s.sprint sp
                    INNER JOIN sp.projectRelease pr
                    INNER JOIN s.project p
                    INNER JOIN s.feature f
                    WHERE r.id = :id'
                )
                ->setParameter('id', $id)
                ->getOneOrNullResult();
    }
}