<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends EntityRepository
{
    
    public function load($id)
    {
        return $this->getEntityManager()
                ->createQuery('
                    SELECT s, pr, p, ss FROM NeblionScrumBundle:Sprint s
                    INNER JOIN s.projectRelease pr
                    INNER JOIN pr.project p
                    INNER JOIN s.status ss 
                    WHERE s.id = :id')
                ->setParameter('id', $id)
                ->getOneOrNullResult();
    }
    
    public function getCurrentForProject($project_id)
    {
        return $this->getEntityManager()
                ->createQuery('
                    SELECT s FROM NeblionScrumBundle:Sprint s
                    INNER JOIN s.projectRelease pr
                    INNER JOIN pr.project p
                    INNER JOIN s.status ss 
                    WHERE p.id = :project_id AND ss.id = 2')
                ->setParameter('project_id', $project_id)
                ->getOneOrNullResult();
    }
    
    public function getList($project_id)
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT s.id, s.name, s.description, ss.name as status, 
                        s.start, s.end,
                        pr.name as release, count(st.id) as stories, 
                        sum(st.estimate) as estimate
                    FROM NeblionScrumBundle:Sprint s
                    INNER JOIN s.status ss
                    INNER JOIN s.projectRelease pr
                    INNER JOIN pr.project p
                    INNER JOIN s.stories st
                    WHERE p.id = :project_id
                    GROUP BY s.id
                    ORDER BY s.created DESC'
                )
                ->setParameter('project_id', $project_id)
                ->getArrayResult();
    }
    
    
    
    public function getStartOfNextSprint($project_id, $startDay)
    {
        $currentSprint = $this->getEntityManager()
                ->createQuery('
                    SELECT s FROM NeblionScrumBundle:Sprint s
                    INNER JOIN s.projectRelease pr
                    INNER JOIN pr.project p
                    INNER JOIN s.status ss 
                    WHERE p.id = :project_id AND ss.id IN (2)')
                ->setParameter('project_id', $project_id)
                ->getOneOrNullResult();
        
        if ($currentSprint) {
            $date = new \DateTime($currentSprint->getEnd()->format('Y-m-d'));
            $date->modify('+1 day');
            return $date;
        } else {
            $date = new \DateTime('now');
            $i = 1;
            while ($i <= 7) {
                if ($date->format('N') == 3) {
                    return $date;
                }
                $date->modify('+1 day');
                $i++;
            }
        }
    }
    
    public function getForRelease($release_id)
    {
        return $this->getEntityManager()
                ->createQuery('
                    SELECT s FROM NeblionScrumBundle:Sprint s
                    INNER JOIN s.projectRelease pr
                    WHERE pr.id = :release_id')
                ->setParameter('release_id', $release_id)
                ->getResult();
    }
}