<?php

namespace Neblion\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function load($id)
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT t, p, m, a, pf
                    FROM NeblionScrumBundle:Team t
                    INNER JOIN t.project p
                    INNER JOIN t.members m
                    INNER JOIN m.account a
                    LEFT JOIN a.profile pf
                    WHERE t.id = :id'
                )
                ->setParameter('id', $id)
                ->getOneOrNullResult();
    }
}