imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ NeblionScrumBundle, FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #lessphp:
        #    file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        #    apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Neblion\ScrumBundle\Entity\Account
    from_email:
        address:        %mailer_address%
        sender_name:    %mailer_sender%
    registration:
        confirmation:
            enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
ornicar_gravatar:
    rating: g
    size: 80
    default: mm

# APLLICATION PARAMETERS
parameters:
  from_email: scrum@neblion.net
  sprint_duration: 13
  sprint_start_day: 3 # mercredi
  default_velocity: 15
  
services:
    neblion_mailer:
      class:  Neblion\ScrumBundle\Mailer\Mailer
      arguments: [@mailer, @router, @templating, { from_email: %from_email% }]
    kernel.listener.neblion_locale:
        class: Neblion\ScrumBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    scrum_activity:
      class:  Neblion\ScrumBundle\Services\Activity
      arguments: [@doctrine.orm.entity_manager]
      
